;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        js2-insert-and-indent
        kill-region
        smex
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-delete-forward
        ))
