;; sre-project.el

(require 'mk-project)

(project-def "nirs"
      '((basedir          "/Users/sre/data/Projects/prod/nirs")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/nirs/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/nirs/files")
        (open-files-cache "/Users/sre/.projects/prod/nirs/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     nirs-startup)
        (shutdown-hook    nil)))

(project-def "playstory"
      '((basedir          "/Users/sre/data/Projects/hackday/playstory")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/hackday/playstory/TAGS")
        (file-list-cache  "/Users/sre/.projects/hackday/playstory/files")
        (open-files-cache "/Users/sre/.projects/hackday/playstory/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     playstory-startup)
        (shutdown-hook    nil)))

(project-def "coderguy"
      '((basedir          "/Users/sre/data/Projects/me/CoderSide")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/me/CoderGuy/TAGS")
        (file-list-cache  "/Users/sre/.projects/me/CoderGuy/files")
        (open-files-cache "/Users/sre/.projects/me/CoderGuy/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     typesafe-startup)
        (shutdown-hook    nil)))

(project-def "merimee"
      '((basedir          "/Users/sre/data/Projects/hackday/merimee")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/hackday/merimee/TAGS")
        (file-list-cache  "/Users/sre/.projects/hackday/merimee/files")
        (open-files-cache "/Users/sre/.projects/hackday/merimee/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     merimee-startup)
        (shutdown-hook    nil)))

(project-def "idoo"
      '((basedir          "/Users/sre/data/Projects/prod/adisseo-crackle")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/idoo/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/idoo/files")
        (open-files-cache "/Users/sre/.projects/prod/idoo/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     idoo-startup)
        (shutdown-hook    nil)))

(project-def "sally"
      '((basedir          "/Users/sre/data/Projects/prod/salesportal/application")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/sally/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/sally/files")
        (open-files-cache "/Users/sre/.projects/prod/sally/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     sally-startup)
        (shutdown-hook    nil)))

(project-def "easy"
      '((basedir          "/Users/sre/data/Projects/prod/easy")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/easy/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/easy/files")
        (open-files-cache "/Users/sre/.projects/prod/easy/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     easy-startup)
        (shutdown-hook    nil)))

(project-def "wroom.io"
      '((basedir          "/Users/sre/data/Projects/prod/wroom.io")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/wroom.io/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/wroom.io/files")
        (open-files-cache "/Users/sre/.projects/prod/wroom.io/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     wroom-startup)
        (shutdown-hook    nil)))

(project-def "wroom-tests"
      '((basedir          "/Users/sre/data/Projects/prod/wroom-tests")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/prod/wroom-tests/TAGS")
        (file-list-cache  "/Users/sre/.projects/prod/wroom-tests/files")
        (open-files-cache "/Users/sre/.projects/prod/wroom-tests/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     wroom-tests-startup)
        (shutdown-hook    nil)))

(project-def "phantomdiff"
      '((basedir          "/Users/sre/data/Projects/me/phantomdiff")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/me/phantomdiff/TAGS")
        (file-list-cache  "/Users/sre/.projects/me/phantomdiff/files")
        (open-files-cache "/Users/sre/.projects/me/phantomdiff/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     phantomdiff-startup)
        (shutdown-hook    nil)))

(project-def "seriez"
      '((basedir          "/Users/sre/data/Projects/hackday/seriez")
        (src-patterns     ("*.scala" "*.js" "*.css" "*.less"))
        (ignore-patterns  ("*.class"))
        (tags-file        "/Users/sre/.projects/hackday/seriez/TAGS")
        (file-list-cache  "/Users/sre/.projects/hackday/seriez/files")
        (open-files-cache "/Users/sre/.projects/hackday/seriez/open-files")
        (vcs              git)
        (compile-cmd      nil)
        (ack-args         nil)
        (startup-hook     seriez-startup)
        (shutdown-hook    nil)))

(defun nirs-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/nirs/dashboard")
)

(defun playstory-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/hackday/playstory")
)

(defun merimee-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/hackday/merimee/mobile-common")
)

(defun typesafe-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/me/CoderSide")
)

(defun idoo-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/adisseo-crackle")
)

(defun sally-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/salesportal/application")
)

(defun easy-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/easy")
)

(defun wroom-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/wroom.io")
)

(defun wroom-tests-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/prod/wroom-tests")
)

(defun phantomdiff-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/me/phantomdiff")
)

(defun seriez-startup ()
  (fuzzy-find-project-root "/Users/sre/data/Projects/hackday/seriez")
)


(provide 'sre-project)
